### ISSUE TITLE
Backwards Compatibility Issues

### ISSUE THREAD

**Issue by Snugug** [IBM-Design/colors#26]
Looking through the code base, the next release is going to be a major breaking change. The reorganization of the repo introduces the following breaking changes:

* Eyeglass will no longer be able to find the Sass file, meaning that anyone using the Node Sass module system will break
* Sass file is no longer a partial, and will generate a CSS file. All module Sass files should be partials, not full files
* JavaScript files no longer in the previous spot, meaning anyone who relies on that will break

**Comment by seejamescode** [comment]
Truth about the breaking changes. There is a lot to consider here. I have reverted the master branch and moved our changes to a v2.0 branch. Now we can consider each piece of the puzzle and improve the "single source of truth"/versioning.

I definitely want the compiled files to all have the same name in the root instead of a dist/ folder. This will also help the experience for non-devs.

@Snugug what is your current view on everything we provide for Sass users? I would like to service as many FEDs as possible with this repo, but within a scope we can reliably provide for.

**Comment by mbarlock** [comment]
If you choose to put everything in the root, you've prevented yourself from automating things. It will work until you need something deleted. Non devs should be able to figure out a folder structure.

**Comment by Snugug** [comment]
Having a src folder and treating root as dist is fine, still allows you to automate.

I'll respond more in depth later this morning.

**Comment by seejamescode** [comment]
Just an update: I believe I have the .sketchpallete and .ase files generating correctly on `gulp` in this branch now. Also, version numbers are updated everywhere (including the package.json) from colors.js.

I am stuck on generating a .clr file though. The file types I mentioned above also need to be tested.

**Comment by seejamescode** [comment]
Closing this because v2.0 resolves it.
