### ISSUE TITLE
Rename "core"?

### ISSUE THREAD

**Issue by seejamescode** [IBM-Design/colors#39]
As of now, we call a different tone for each color the `core` tone. These core tones are actually different for each color. A designer should not decide they are using the cores and assume they are obeying the 50-point accessibility rule. This collection of core tones simply look most appealing when together on a color wheel.

My question here: Is `core` the correct word for this? Are there any suggestions for alternatives?

**Comment by cuyaproductions** [comment]
Since all of the other tones are numbers in increment of 10, my initial incline would be to label it `0`. I'm not sure that gets at what you're wanting to solve.

**Comment by matthewcpaul** [comment]
0 doesn't make sense. They already exist as a power of 10 numeral. 

James, I found this quite odd when examining 2.0.0, but assumed a "core" color was pulled out to represent what is now the lowest number that you can safely use in or against white. If that's not the intent, then I question what the intent is. "Because they look good together on a color wheel" doesn't seem like the right intent. Does that actually help the designers this is meant for?

**Comment by seejamescode** [comment]
Right, you are describing what most FED reactions are to the core tones. However, it has value to the visual designers as a highlight, presentational, or signature tone of each color (some words we've been throwing around). There is not a single tone that looks best across all of the colors we have.

**Comment by seejamescode** [comment]
I had a thought last night actually. What if instead of listing it as a hex, we lift it up in the object and say which tone it is. This way we have the value of it be recognized while teaching us FEDs that it is a variety of tones:

Before:
```
{
  name: 'ultramarine',
  synonyms: ['cool-blue'],
  values: [
    { tone: 'core', value: '#3151b7' },
    { tone: '1', value: '#e7e9f7' },
    { tone: '10', value: '#d1d7f4' },
    { tone: '20', value: '#b0bef3' },
    { tone: '30', value: '#89a2f6' },
    { tone: '40', value: '#648fff' },
    { tone: '50', value: '#3c6df0' },
    { tone: '60', value: '#3151b7' },
    { tone: '70', value: '#2e3f8f' },
    { tone: '80', value: '#252e6a' },
    { tone: '90', value: '#20214f' }
  ]
}
```

After:
```
{
  name: 'ultramarine',
  synonyms: ['cool-blue'],
  core: '60',
  values: [
    { tone: '1', value: '#e7e9f7' },
    { tone: '10', value: '#d1d7f4' },
    { tone: '20', value: '#b0bef3' },
    { tone: '30', value: '#89a2f6' },
    { tone: '40', value: '#648fff' },
    { tone: '50', value: '#3c6df0' },
    { tone: '60', value: '#3151b7' },
    { tone: '70', value: '#2e3f8f' },
    { tone: '80', value: '#252e6a' },
    { tone: '90', value: '#20214f' }
  ]
}
```

Does this sound good?

**Comment by matthewcpaul** [comment]
That makes more systematic sense in terms of using the function. But, what's the purpose of core? What's a *real* use case of a visual designer using it? Is it to help them understand contrast ratio (that's what the 50s used to represent), because that would actually be helpful.

**Comment by shagadorn** [comment]
I seem to remember it being more of a development idea. So that if they wanted to only specify "yellow" you would get the ideal yellow (yellow 20). But I think this detracts from the grade system, and is somewhat confusing. 

Maybe there could be more of a system where people choose colors for their projects and assign them variables like "core" or "primary" , "background" , "warning". We do this with our color palette system for Analytics Solutions.

**Comment by jordaniusrex** [comment]
@matthewcpaul I see the use case like this: I want to build a color palette based primarily around yellow. I have to consider that pure colors appear brighter than each other depending on the hue, so "yellow" inherently appears brighter than "blue." The "core" color yellow, Yellow 10, gives me a starting point that is identifiable as yellow. Yellow 50, the middle grade that works with acceptable contrast against both black and white, isn't a color that anyone would call yellow—it's more of an "olive drab." There isn't a single grade that will look "pure" across all colors. Knowing that "core" yellow is Yellow 10, I can then make decisions about what other grades I need to use in my color system to provide contrast against that yellow.

I like your suggestion @seejamescode for identifying which grade is the core color rather than specifying its exact value because it's closer to how a designer thinks about choosing colors.

If people are confused by the "core" term, "signature" is a good term for it… Maybe "basic," "simple," "foundation," or "key" would work as well.
