### ISSUE TITLE
Color contrast for warmer colors

### ISSUE THREAD

**Issue by derrickligon** [IBM-Design/colors#46]
When viewed as a whole set there is a section of the palette where certain colors seem darker and/or more saturated than the neighboring colors of the same grade. Was unsure if this was needed for accessibility reasons that relate to warm colors so partially was just looking for some clarification

![color-contrast](https://cloud.githubusercontent.com/assets/23021094/21119445/3bab754a-c088-11e6-84c7-ceec9f412671.png)

**Comment by jordaniusrex** [comment]
Good eye—what you're noticing is an intentional decision based on an effect of the inherent brightness of each hue and the design goal for a rich, harmonious set of core colors. Perceived brightness varies based on the hue and saturation of each color (in addition to the lightness). For example, yellow is brighter than orange which is brighter than red. Since each grade in this system has a target contrast value, the hues were selected on the full spectrum so that a saturated core color hue would align with a particular grade. The dropoff in saturation happens on certain colors because of limits to the color gamut (i.e. you can't get a more saturated orange at that grade) or to blend to the darker values more evenly.

**Comment by derrickligon** [comment]
Thanks for responding, Jordan! That was very helpful/insightful. I initially assumed it was intentional but wanted to make sure.
