### ISSUE TITLE
differentiating between colors

### ISSUE THREAD

**Issue by derrickligon** [IBM-Design/colors#47]
some pairs of neighboring colors of the same general hue seem to be much closer than others and are somewhat difficult to distinguish from each other. Knowing they would most likely never be used together, it may be worth taking a look

![color-bleed](https://cloud.githubusercontent.com/assets/23021094/21120012/d6531a6a-c08a-11e6-9541-dbf989fc39e5.png)

**Comment by jordaniusrex** [comment]
The proximity of neighboring hues a tradeoff between distinguishability of colors around the core grades, the aesthetic appeal and brightness of the core colors, the common associations with the "name" of the color, compatibility with the existing system, and requests from end users. Because, like you said, Ultramarine 50 and Blue 50 wouldn't likely be used in the same design, there's a benefit to providing alternative warmer and cooler blues (that could complement differently with warmer colors) instead of more widely distributed hues.

Here is an illustration of the distribution of the colors at 50 Grade:

![50-grade-spectrum-distribution](https://cloud.githubusercontent.com/assets/611304/21649849/b50e4a7e-d268-11e6-9565-6ceb4faab411.png)

How would having more differentiated hues at particular grades be useful to you in your work?

**Comment by derrickligon** [comment]
My concern was more with how having less differentiated hues may make the decision making process for colors more difficult and lead to some inconsistencies in products. I know that the expanded palette is meant to help with data vis palettes, but the lack of differentiation between hues at particular grades makes certain portions of neighboring hues seem duplicative, but that isn't true for all the hues. 

I understand the wider distributed (or more differentiated) hues, but I guess I'm more curious about the overall benefit of the more narrowly distributed hues specifically to the end user and the reasoning behind those few narrow distributions. If most end users (and some designers) aren't going to recognize the nuances between how three blue temperatures complement with warmer colors or the difference between our red and orange (whether that's vision or device/screen quality) is it a benefit or a hindrance for designers?

**Comment by jordaniusrex** [comment]
Yeah, it's definitely a tradeoff between making decisions simpler for designers, providing the flexibility for nuance, and accommodating expectations. The specific hues chosen for the core colors were based on feedback from product teams and marketing stakeholders about the existing color system and what would be useful for their design needs: e.g. making adjustments to the primary blue color and providing warmer and cooler versions of it to be used in combinations. A good approach to making clear decisions about the colors is to create a color scheme based on a few specific values and then adjusting the lightness and darkness grades as needed.
