### ISSUE TITLE
Filename versioning

### ISSUE THREAD

**Issue by NohWayJose** [IBM-Design/colors#63]
(despite my non-ibm login, I am an IBM designer at Hursley Studio - Greg Lubel)

Please will you include a naming convention in the filenames, so it's easier to pick up the right one from my Downloads folder

**Comment by seejamescode** [comment]
Hi @NohWayJose! Versioning is left to our [repo's releases](https://github.com/IBM-Design/colors/releases) and [node module](https://www.npmjs.com/package/ibm-design-colors). This is so that a developer can upgrade a product to the latest version without changing file paths.

If you download from the [repo's release page](https://github.com/IBM-Design/colors/releases), the download version will be numbered.

Hope this helps,
James
