### ISSUE TITLE
Document the value names

### ISSUE THREAD

**Issue by kevinSuttle** [IBM-Design/colors#7]
i.e. What exactly is  `blue-10`, and how is `blue-core` different than `blue-100`?

**Comment by kevinSuttle** [comment]
I thought about running these values through a PostCSS plugin to see of there were CSS Color names that make any more sense. @jonathantneal generously offered to build one. 

https://twitter.com/kevinSuttle/status/674286563698876416

**Comment by kevinSuttle** [comment]
I think this is the beginning of that, but so far, none of our colors have a CSS Color name. https://github.com/jonathantneal/closest-color

**Comment by mbarlock** [comment]
The page that explains the colors are in the [design guide](http://www.ibm.com/design/language/framework/visual/color#contrast). "core" is anyone's guess. I think it was the color used as the big headings on the design language website.

**Comment by kevinSuttle** [comment]
Aha, so `core` is also the same value as `50`.

**Comment by kevinSuttle** [comment]
I noticed that Google's Material colors are similar in scale. 
https://www.google.com/design/spec/style/color.html

**Comment by jonathantneal** [comment]
So, this might seem random, but every weekend I try to release a PostCSS plugin that would help with exactly this situation. It can match every color in your CSS to a palette of your choice, either producing a list of palette approved colors and the number of times they are used, or nearly the same list, except including variations like matching-color-variation-1, matching-color-variation-2, matching-color-variation-3 for every inexact match.

But ... I keep hitting the same brick wall. And it might seem really silly, ok? But hey, in off hours open source, stupid stuff can delay you hours to years. My issue is: What exactly should be exported? Do I produce a JSON file of color keys and the number of times they appear? Some kind of text report? Another CSS file?

Since you inspired this, I was hoping you might know what you wanted, even if you’re no longer interested, necessarily. I still think you had a great idea, and it could help a lot of people.

**Comment by kevinSuttle** [comment]
Thanks @jonathantneal. What we have is a set of core colors (this repo), that each product team uses as a base for their branding. The issue becomes that the disconnect between the 2 happens very easily. Even here, we can see multiple definitions of the same value over and over. The connection is what we're after when I say "single sourcing".

**Comment by kevinSuttle** [comment]
@jonathantneal Seems @ dcwarwick did this: https://github.com/IBM-Design/colors/commit/ba053a52c371db278e0dd528cee746615c5e0347#diff-6a853a1f7639b0af7520dddefa30c2ffR18
